# Dutch-to-English translation mappings for CERM schema
# Common abbreviations: ref=reference, oms=description, dat=date, nr=number, art=article, aant=quantity, etc.
#
# HOW TO USE
# ----------
# 1. Run from the Documentation folder:
#    cd Documentation
#    .\translate-cerm-schema.ps1
#
# 2. The script reads CERM_tables_columns.json, populates ENG_TABLE and ENG_COLUMN for each row,
#    and overwrites the JSON file.
#
# 3. To add or adjust translations, edit the mappings below:
#    - $tableMap: full table names (e.g. 'stnspr__' -> 'DieStation')
#    - $columnPartMap: column name parts for composite translation
#    - $columnFullMap: exact column names for direct translation

$tableMap = @{
    'a_track_ship' = 'TrackingShipment'
    'afdel___' = 'Department'
    'afdohk__' = 'DepartmentOverhead'
    'afgafw__' = 'DeliveryFinishing'
    'afgant__' = 'DeliveryQuantity'
    'afgart__' = 'DeliveryArticle'
    'afgbew__' = 'DeliveryOperation'
    'afgbjr__' = 'DeliveryFiscalYear'
    'afgbox__' = 'DeliveryBox'
    'afgclt__' = 'DeliveryCollation'
    'afgcmb__' = 'DeliveryCombination'
    'afgcmd__' = 'DeliveryCommand'
    'afgcmo__' = 'DeliveryComment'
    'afgext__' = 'DeliveryExtension'
    'afgfac__' = 'DeliveryInvoice'
    'afginf__' = 'DeliveryInfo'
    'afgkjr__' = 'DeliveryCalendarYear'
    'afgklm__' = 'DeliveryCalendarMonth'
    'afgklr__' = 'DeliveryColor'
    'afgkst__' = 'DeliveryCost'
    'afgmnd__' = 'DeliveryMonth'
    'afgovp__' = 'DeliveryOverprint'
    'afgper__' = 'DeliveryPeriod'
    'afgprd__' = 'DeliveryPeriod'
    'afgpry__' = 'DeliveryPrice'
    'afgres__' = 'DeliveryResidue'
    'afgsku__' = 'DeliverySku'
    'afgsms__' = 'DeliverySms'
    'afgvdt__' = 'DeliveryDistribution'
    'afgvrd__' = 'DeliveryStock'
    'artikd__' = 'ArticleDate'
    'artiky__' = 'ArticleKey'
    'artinf__' = 'ArticleInfo'
    'artikn__' = 'ArticleNumber'
    'artikp__' = 'ArticlePrice'
    'artkla__' = 'ArticleClass'
    'artlev__' = 'ArticleLevel'
    'besbon__' = 'OrderSlip'
    'betkon__' = 'PaymentTerms'
    'betwij__' = 'PaymentMethod'
    'boekja__' = 'FiscalYear'
    'bstafr__' = 'OrderReference'
    'bstlyn__' = 'OrderLine'
    'bstprd__' = 'OrderProduct'
    'bstext__' = 'OrderText'
    'budget__' = 'Budget'
    'dagbkn__' = 'Journal'
    'drg_bk__' = 'DrawingBook'
    'drgdgm__' = 'DrawingDiagram'
    'drgtyp__' = 'DrawingType'
    'drk_dg__' = 'PrintDesign'
    'fak____' = 'Invoice'
    'lev____' = 'Delivery'
    'palet___' = 'Pallet'
    'stnspr__' = 'DieStation'
    'stnspr___' = 'DieStation'
    'v1bon___' = 'OrderHeader'
    'vak_____' = 'Compartment'
}

# Column suffix/word mappings (applied to parts of column names)
$columnPartMap = @{
    'aant' = 'Quantity'
    'aant_rol' = 'QuantityRoll'
    'aantprol' = 'QuantityPerRoll'
    'aantal' = 'Quantity'
    'afd' = 'Department'
    'afg' = 'Delivery'
    'afw' = 'Finishing'
    'akp' = 'PurchasePrice'
    'arth' = 'ArticleHelp'
    'art' = 'Article'
    'awp' = 'FinishingType'
    'awst' = 'FinishingType'
    'bedr' = 'Amount'
    'bedv' = 'AmountValue'
    'begi' = 'Start'
    'behoefte' = 'Requirement'
    'best' = 'Order'
    'bew' = 'Operation'
    'bjr' = 'FiscalYear'
    'bm' = 'Booked'
    'bon' = 'Order'
    'box__ref' = 'BoxReference'
    'crea' = 'Created'
    'crea_dat' = 'CreationDate'
    'crea_uur' = 'CreationTime'
    'crea_usr' = 'CreatedBy'
    'comment' = 'Comment'
    'dat' = 'Date'
    'dat__inv' = 'InvoiceDate'
    'datum' = 'Date'
    'dos__ref' = 'DossierReference'
    'drg' = 'Drawing'
    'etas' = 'ETA'
    'ex___rol' = 'ExtraRoll'
    'hoev' = 'Amount'
    'in_best_' = 'OnOrder'
    'in_produ' = 'InProduction'
    'in___qrt' = 'InQuarter'
    'inhoud' = 'Content'
    'inleesnr' = 'ReadNumber'
    'jobnr' = 'JobNumber'
    'kjr' = 'Year'
    'kl' = 'Class'
    'kla__ref' = 'ClassReference'
    'klgr' = 'ClassGroup'
    'klm' = 'CalendarMonth'
    'klwlkst' = 'ColorCost'
    'koers' = 'ExchangeRate'
    'komment' = 'Comment'
    'kommiss' = 'Commissioned'
    'kst' = 'Cost'
    'l_akp___' = 'LastPurchasePrice'
    'lbn' = 'OrderNumber'
    'lever' = 'Delivery'
    'lev__dat' = 'DeliveryDate'
    'lev__ref' = 'DeliveryReference'
    'lev__uur' = 'DeliveryTime'
    'lock' = 'Lock'
    'loc__stk' = 'StockLocation'
    'materie' = 'Material'
    'mnd' = 'Month'
    'munt_ref' = 'CurrencyReference'
    'nr' = 'Number'
    'om2' = 'Description2'
    'oms' = 'Description'
    'omschr' = 'Description'
    'omzet' = 'Turnover'
    'ord__ref' = 'OrderReference'
    'overprod' = 'Overproduction'
    'pal__ref' = 'PalletReference'
    'perc' = 'Percentage'
    'plwlkst' = 'PlateCost'
    'pr_excl' = 'PriceExclVat'
    'pr_incl' = 'PriceInclVat'
    'prd' = 'Period'
    'prod' = 'Production'
    'prys' = 'Price'
    'qrt' = 'Quarter'
    'ref' = 'Reference'
    'res' = 'Residue'
    'rol_doos' = 'RollsPerBox'
    'rowid' = 'RowId'
    'rpn' = 'Reproduction'
    'srt' = 'Type'
    'stafflpr' = 'StaffelPrice'
    'stck' = 'Stock'
    'stns' = 'Die'
    'strtkst' = 'StraightCost'
    'te_lever' = 'ToDeliver'
    'toestand' = 'Status'
    'typ' = 'Type'
    'uit__dat' = 'ExitDate'
    'uit__uur' = 'ExitTime'
    'uit__usr' = 'ExitedBy'
    'uitg' = 'Exhausted'
    'uitgeput' = 'Exhausted'
    'user' = 'User'
    'usergrp' = 'UserGroup'
    'vak' = 'Compartment'
    'vdt' = 'Distribution'
    'vdt__ref' = 'DistributionReference'
    'versi' = 'Version'
    'volg' = 'Order'
    'volgorde' = 'Sequence'
    'vprc' = 'SalesPrice'
    'vrd' = 'Stock'
    'vrpl' = 'Replacement'
    'vrrd' = 'Stock'
    'vrz' = 'Reserve'
    'wijze' = 'Method'
    'zynrefkl' = 'CustomerReferenceClass'
    'zyde' = 'Side'
}

# Full column name mappings (exact match)
$columnFullMap = @{
    'aantal__' = 'Quantity'
    'afd__kst' = 'DepartmentCost'
    'afd__om2' = 'DepartmentDescription2'
    'afd__oms' = 'DepartmentDescription'
    'afd__ref' = 'DepartmentReference'
    'afd_vprc' = 'DepartmentSalesPrice'
    'afg2_ref' = 'DeliveryReference2'
    'afg__ref' = 'DeliveryReference'
    'afg__rpn' = 'DeliveryReproduction'
    'afg_oms1' = 'DeliveryDescription1'
    'afg_oms2' = 'DeliveryDescription2'
    'art__ref' = 'ArticleReference'
    'art__rpn' = 'ArticleReproduction'
    'arth_ref' = 'ArticleHelpReference'
    'awst_ref' = 'FinishingTypeReference'
    'afwp_ref' = 'FinishingTypeReference'
    'afw__ref' = 'FinishingReference'
    'afw_zyde' = 'FinishingSide'
    'bar__ref' = 'BarcodeReference'
    'b_akp_vm' = 'BasePurchasePrice'
    'bdgt_ref' = 'BudgetReference'
    'bedrag__' = 'Amount'
    'behoefte' = 'Requirement'
    'bkj__ref' = 'FiscalYearReference'
    'bon__ref' = 'OrderReference'
    'bon__rpn' = 'OrderReproduction'
    'box__ref' = 'BoxReference'
    'btw_def_' = 'DefaultVat'
    'cost' = 'Cost'
    'costpkg' = 'CostPerPackage'
    'crea_dat' = 'CreationDate'
    'crea_uur' = 'CreationTime'
    'crea_usr' = 'CreatedBy'
    'dat_begi' = 'StartDate'
    'dat_stck' = 'StockDate'
    'dat__vrz' = 'ReserveDate'
    'dat_uitg' = 'ExhaustedDate'
    'datum___' = 'Date'
    'dgbk_ref' = 'DrawingBookReference'
    'dos__ref' = 'DossierReference'
    'dossier_' = 'Dossier'
    'drg__ref' = 'DrawingReference'
    'drg_vrpl' = 'DrawingReplacement'
    'ean___nr' = 'EANNumber'
    'etas_ref' = 'ETAReference'
    'ext__ref' = 'ExternalReference'
    'fac_dflt' = 'DefaultInvoice'
    'halffabr' = 'SemiFinished'
    'id' = 'Id'
    'in_best_' = 'OnOrder'
    'in_produ' = 'InProduction'
    'in___qrt' = 'InQuarter'
    'in__vrrd' = 'InStock'
    'in_ex_il' = 'InlineExInline'
    'inhoud01' = 'Content01'
    'inhoud02' = 'Content02'
    'kla__ref' = 'ClassReference'
    'kla__rpn' = 'ClassReproduction'
    'klgr_ref' = 'ClassGroupReference'
    'klm__ref' = 'CalendarMonthReference'
    'knp__ref' = 'NodeReference'
    'komment2' = 'Comment2'
    'komment_' = 'Comment'
    'kort_akp' = 'DiscountPurchasePrice'
    'krit___1' = 'Criterion1'
    'krit___2' = 'Criterion2'
    'l_akp___' = 'LastPurchasePrice'
    'lev__dat' = 'DeliveryDate'
    'lev__ref' = 'DeliveryReference'
    'lev__rpn' = 'DeliveryReproduction'
    'lev__uur' = 'DeliveryTime'
    'lock_usr' = 'LockUser'
    'materie_' = 'Material'
    'method' = 'Method'
    'multipart' = 'Multipart'
    'munt_ref' = 'CurrencyReference'
    'oms_aant' = 'QuantityDescription'
    'omschr__' = 'Description'
    'omzet_bm' = 'TurnoverBooked'
    'omzet_wy' = 'TurnoverMethod'
    'ord__ref' = 'OrderReference'
    'overprod' = 'Overproduction'
    'pal__ref' = 'PalletReference'
    'percent_' = 'Percentage'
    'per_hoev' = 'PerAmount'
    'pr_excl_' = 'PriceExclVat'
    'pr_incl_' = 'PriceInclVat'
    'prys_srt' = 'PriceType'
    'prys_typ' = 'PriceKind'
    'rowid' = 'RowId'
    'shipdate' = 'ShipDate'
    'sms__typ' = 'SmsType'
    'soort___' = 'Type'
    'stns_oms' = 'DieDescription'
    'stns_ref' = 'DieReference'
    'stx__srt' = 'TaxType'
    'supplier' = 'Supplier'
    'te_lever' = 'ToDeliver'
    'tracknr' = 'TrackingNumber'
    'tracknrpkg' = 'TrackingNumberPackage'
    'uit__dat' = 'ExitDate'
    'uit__uur' = 'ExitTime'
    'uit__usr' = 'ExitedBy'
    'uitgeput' = 'Exhausted'
    'usergrp_' = 'UserGroup'
    'user____' = 'User'
    'uuid' = 'Uuid'
    'vak__ref' = 'CompartmentReference'
    'vdt__ref' = 'DistributionReference'
    'versiref' = 'VersionReference'
    'void' = 'Void'
    'volgorde' = 'Sequence'
    'vkp___vm' = 'SalesPrice'
    'vrijdat1' = 'FreeDate1'
    'vrijveld' = 'FreeField'
    'vrijvel2' = 'FreeField2'
    'vrz_dflt' = 'DefaultStock'
    'vrt__ref' = 'VariantReference'
    'wijze___' = 'Method'
    'weight' = 'Weight'
    'zyn__ref' = 'CustomerReference'
}

function Get-EngTable {
    param([string]$tableName)
    if ($tableMap.ContainsKey($tableName)) { return $tableMap[$tableName] }
    # Apply common prefixes
    $t = $tableName -replace '^afdel', 'Department' -replace '^afg', 'Delivery' -replace '^art', 'Article'
    $t = $t -replace '^bst', 'Order' -replace '^bes', 'Order' -replace '^bud', 'Budget'
    $t = $t -replace '^drg', 'Drawing' -replace '^lev', 'Delivery' -replace '^fak', 'Invoice'
    $t = $t -replace '^stns', 'Die' -replace '^v1bon', 'Order' -replace '^vak', 'Compartment'
    $t = $t -replace '^palet', 'Pallet' -replace '^boek', 'Book' -replace '^dagb', 'Journal'
    $t = $t -replace '_+$', '' -replace '__', '_'
    if ($t -ne $tableName) { return $t }
    return ''
}

function Get-EngColumn {
    param([string]$colName)
    if ($columnFullMap.ContainsKey($colName)) { return $columnFullMap[$colName] }
    $parts = $colName -split '_'
    $translated = @()
    foreach ($p in $parts) {
        $clean = $p -replace '_+$' -replace '^_+'
        if ($clean -eq '') { continue }
        if ($columnPartMap.ContainsKey($clean)) {
            $translated += $columnPartMap[$clean]
        } elseif ($clean -match '^\d+$') {
            $translated += $clean
        } else {
            $translated += $clean
        }
    }
    $result = ($translated | Where-Object { $_ -ne '' }) -join '_'
    if ($result -ne '' -and $result -ne $colName) { return $result }
    return ''
}

# Load JSON, translate, save
$json = Get-Content -Path "CERM_tables_columns.json" -Raw -Encoding UTF8 | ConvertFrom-Json
$count = 0
foreach ($row in $json) {
    $count++
    $row.ENG_TABLE = Get-EngTable $row.TABLE_NAME
    $row.ENG_COLUMN = Get-EngColumn $row.COLUMN_NAME
    if ($count % 5000 -eq 0) { Write-Host "Processed $count rows..." }
}
$json | ConvertTo-Json -Depth 10 -Compress | Out-File -FilePath "CERM_tables_columns.json" -Encoding UTF8 -Force
Write-Host "Done. Translated $count rows."
